FROM php:8.2.7-fpm-alpine3.18

COPY . .

# Image config
ENV SKIP_COMPOSER 1
ENV WEBROOT /var/www/html/public
ENV PHP_ERRORS_STDERR 1
ENV RUN_SCRIPTS 1
ENV REAL_IP_HEADER 1

# Laravel config
ENV APP_NAME="MinBillz"
ENV APP_ENV=local
ENV APP_KEY=base64:ptdG0XXzacjXpfs836FUVgZcBLbss3MCC1WZwmERVhU=
ENV APP_DEBUG=true
ENV APP_TIMEZONE=UTC
ENV APP_URL=http://localhost:1211
ENV APP_CODE=MNB

ENV APP_LOCALE=en
ENV APP_FALLBACK_LOCALE=en
ENV APP_FAKER_LOCALE=en_US

ENV APP_MAINTENANCE_DRIVER=file
ENV APP_MAINTENANCE_STORE=database

ENV BCRYPT_ROUNDS=12

ENV LOG_CHANNEL=stack
ENV LOG_STACK=single
ENV LOG_DEPRECATIONS_CHANNEL=null
ENV LOG_LEVEL=debug

ENV DB_CONNECTION=pgsql
ENV DB_HOST=postgresql://min_billz_db_user:NxLpdKHLyalCCfZ6FQTdXslD9S2dzemO@dpg-crpv3obv2p9s738d053g-a/min_billz_db
ENV DB_PORT=5432
ENV DB_DATABASE=min_billz_db
ENV DB_USERNAME=min_billz_db_user
ENV DB_PASSWORD="NxLpdKHLyalCCfZ6FQTdXslD9S2dzemO"

ENV SESSION_DRIVER=database
ENV SESSION_LIFETIME=120
ENV SESSION_ENCRYPT=false
ENV SESSION_PATH=/
ENV SESSION_DOMAIN=null

ENV BROADCAST_CONNECTION=log
ENV FILESYSTEM_DISK=local
ENV QUEUE_CONNECTION=database

ENV CACHE_STORE=database
ENV CACHE_PREFIX=

ENV MEMCACHED_HOST=127.0.0.1

ENV REDIS_CLIENT=phpredis
ENV REDIS_HOST=127.0.0.1
ENV REDIS_PASSWORD=null
ENV REDIS_PORT=6379

ENV MAIL_MAILER=smtp
ENV MAIL_HOST=node.webproserver.com
ENV MAIL_PORT=465
ENV MAIL_USERNAME=info@errandmate.ng
ENV MAIL_PASSWORD="h9Z0@}Nk%avO"
ENV MAIL_ENCRYPTION=ssl
ENV MAIL_FROM_ADDRESS=info@errandmate.ng
ENV MAIL_FROM_NAME="${APP_NAME}"
ENV MAIL_TO=support@errandmate.ng
ENV MAIL_APP_SUPPORT=smallkid1@yahoo.com

ENV AWS_ACCESS_KEY_ID=
ENV AWS_SECRET_ACCESS_KEY=
ENV AWS_DEFAULT_REGION=us-east-1
ENV AWS_BUCKET=
ENV AWS_USE_PATH_STYLE_ENDPOINT=false

ENV VITE_APP_NAME="${APP_NAME}"

ENV MONNIFY_API_KEY=MK_TEST_3ULC0UWHPN
ENV MONNIFY_API_SECRET=74LH7TTRZRJRMWB4A95S12GK7XWPDS7E
ENV MONNIFY_API_URL=https://sandbox.monnify.com/api
ENV MONNIFY_CONTRACT_CODE=0519494214

ENV PAYSTACK_API_URL=https://api.paystack.co
ENV PAYSTACK_PAYMENT_URL=https://api.paystack.co
ENV PAYSTACK_PUBLIC_KEY=pk_test_99139a1d024c2b41386ed4cd6b89cebe8e59b73a
ENV PAYSTACK_SECRET_KEY=sk_test_b13c1a7afde2c5651aef1919c9973aa2aebedfc5
ENV PAYSTACK_CALLBACK_URL="${APP_URL}/transactions/verify/:transid"

ENV GSUBZ_API_URL=https://gsubz.com/api
ENV GSUBZ_APP_CODE=gsubz
ENV GSUBZ_API_KEY=ap_2a85f0868e29b37f62e4b711da21d697
ENV GSUBZ_WIDGET_KEY=wd_13e0403559c55e38572a54afc7f90d3c

ENV PAGINATION_COUNT=100

# Allow composer to run as root
ENV COMPOSER_ALLOW_SUPERUSER 1

CMD ["/start.sh"]
